//CRIAR USUÁRIO
POST http://localhost/charly/cliente.php
Content-Type: application/json

{
    "nome": "João",
    "sobrenome": "Silva",
    "email": "joao@example.com",
    "telefone": "(11) 99999-9999"
}



//LISTAR TODOS
###

GET http://localhost/charly/cliente.php



//BUSCAR POR ID
###

GET http://localhost/charly/cliente.php?id=1



//ATUALIZAR
###
PUT http://localhost/charly/cliente.php?id=1
Content-Type: application/json

{
    "nome": "João Atualizado",
    "sobrenome": "Silva",
    "email": "joao_novo@example.com",
    "telefone": "(11) 98888-7777"
}


//DELETAR
### 
DELETE http://localhost/charly/cliente.php?id=1
